logging:
    level:
        ROOT: INFO
        org.alma.authentification: DEBUG
spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        platform: h2
        url: jdbc:h2:file:./target/h2db/db/dbh2;DB_CLOSE_DELAY=-1
        username: MakeMyApp
        password:
        hikari:
            auto-commit: false
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        hibernate:
          ddl-auto: update
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
security:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800           
