DELETE FROM STD_USER_AUTHORITY;
DELETE FROM STD_USER;
INSERT INTO STD_USER(id,FULL_NAME,PASSWORD_HASH,USERNAME) VALUES(0,'admin','$2a$10$SIJfyTEY9xoNsXA4nTT27uPKaOeJp5PMm.ZoBEyYPqEra..4FsXp2','admin');
